on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

name: Create Release

jobs:
  windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Test
      #   run: cargo test --release
      - name: Build
        run: cargo build --release

      - name: "Filename"
        run: |
          mkdir outputs
          echo HERE COMES THE SUN
          ls
          echo END OF THIS THING
          cp target/release/sickomode.exe outputs/rcat-${{github.ref_name}}-portable.exe

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.14
        with:
          # generate_release_notes: true
          # draft: false
          # prerelease: false
          files: |
            outputs/**
