on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run commands
        uses: uraimo/run-on-arch-action@v2.1.1
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu18.04

          githubToken: ${{ github.token }}
          
          # To explore the enviroment
          install: |
            apt-get update -y
            apt-get install -y python3-pip python3
            pip3 install --upgrade pip
            pip3 install meson ninja

          run: |
            echo yo

      - name: Get the output
        run: |
          echo finished
          
      # - name: Create Release
      #   id: create_release
      #   uses: softprops/action-gh-release@v0.1.14
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     generate_release_notes: true
      #     draft: false
      #     prerelease: false
